name: Test all actions
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get today string
        uses: DanielRNDev/get-today@v1.0.0
        id: today-string
      - name: Use today string
        env:
          TODAY: "${{ steps.today-string.outputs }}"
        run: echo $TODAY
